from pydantic import BaseModel, Field


class AgentMessageRequest(BaseModel):
    """
    Request body accepted by the agent messaging endpoint.
    """

    message: str = Field(
        ...,
        min_length=1,
        max_length=20000,
        description="User message to send to the configured Foundry agent.",
    )

    conversation_id: str | None = Field(
        default=None,
        description=(
            "Existing Foundry conversation ID used to continue a conversation. "
            "Omit this value to start a new conversation."
        ),
    )


class AgentMessageResponse(BaseModel):
    """
    Response returned after executing a message through Microsoft Agent Framework.
    """

    request_id: str | None = Field(
        default=None,
        description="Request correlation ID generated by FastAPI middleware.",
    )

    agent_name: str = Field(
        ...,
        description="Name of the Foundry Prompt Agent requested in the API route.",
    )

    foundry_agent_name: str = Field(
        ...,
        description="Name of the existing Foundry Prompt Agent invoked.",
    )

    agent_version: str | None = Field(
    default=None,
    description=(
        "Explicit Foundry agent version invoked by the API. "
        "Null means the latest active Foundry version was requested."
    ),
    )

    conversation_id: str = Field(
        ...,
        description=(
            "Foundry conversation ID. Pass this value in the next request "
            "to continue the same conversation."
        ),
    )

    response_text: str = Field(
        ...,
        description="Text response returned by the Foundry agent.",
    )